[VAS-864] feat: add user and groups to bo nav
pagopa/pagopa-selfcare-frontend pull request #429
Opened 2024-04-08 09:18 UTC by alessio-cialini

#### List of Changes

- Introduced users and groups redirection on back office side-menu

#### Motivation and Context

https://pagopa.atlassian.net/browse/VAS-864

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-04-08 10:27 UTC, jacopocarlini commented on src/components/SideMenu/SideMenu.tsx
> +                    {ENV.FEATURES.DASHBOARD.ENABLED && (
```suggestion
                    { (
```

2024-04-08 10:27 UTC, jacopocarlini commented on src/components/SideMenu/SideMenu.tsx
> +
add a divider

2024-04-08 10:29 UTC, jacopocarlini requested changes
add the divider

2024-04-09 07:21 UTC, svariant approved these changes
💪🏻

2024-04-09 07:33 UTC, jacopocarlini approved these changes

2024-04-09 07:33 UTC, merged