[VAS-1059] feat: Update CI station association form
pagopa/pagopa-selfcare-frontend pull request #524
Opened 2024-05-30 07:52 UTC by gioelemella

#### List of Changes

- refactor CI station association form
- moved add broker to available delegations logic to backend
- fixed enable submit button logic

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-05-30 14:27 UTC, svariant approved these changes
🚀 🕒

2024-05-31 08:04 UTC, jacopocarlini commented on .github/workflows/release_deploy.yml
> +          skip_ci: false
```suggestion
          skip_ci: true
```

2024-05-31 08:08 UTC, jacopocarlini commented
<img width="1022" alt="Screenshot 2024-05-31 alle 10 07 05" src="https://github.com/pagopa/pagopa-selfcare-frontend/assets/13539513/de3bbccd-83e9-4afd-987c-32e5fdb418fd">
I found these wrong labels

2024-05-31 08:08 UTC, jacopocarlini requested changes
see the comment

2024-05-31 12:59 UTC, merged